functional:
  - Игрок может зарегистрироваться на сайте
  - Игрок может войти в свою учетную запись и выйти из нее
  - Игрок может выбрать уровень сложности
  - Игрок может выбрать соперника, то есть бота или другого игрока
  - Все пользователи могут видеть решения других игроков
  - Игрок может выбрать время соревнований
  - Игрок может увидеть рейтинг
  - Игрок может выбрать язык програмирования
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Игра должна завершаться либо победой одого из игроков, либо ничьей
