functional:
  - Игрок может зарегистрироваться на сайте
  - Игрок может войти в свою учетную запись и выйти из нее
  - Игрок может выбрать уровень сложности
  - Игрок может выбрать соперника, то есть бота или другого игрока
  - Все пользователи могут видеть решения других игроков
  - Игрок может выбрать время соревнований
  - Игрок может увидеть рейтинг
  - Игрок может выбрать язык програмирования
  - Игрок может приглашать других игроков
  - Игрок может настраивать тип соревнований
  - Игрок может создавать игры без регистрации
  - Игрок может присоединяться к другим играм
  - Игрок может видеть 2 редактора - свой и чужой
  - Игроки могут отправлять сообщения в чат
  - Игрок может отправить задание на проверку
  - Игрок может переподключиться в игру 
  - Игрок может видеть задание к игре 
  - Игра заканчивается, когда кто-то из игроков решил задание
  - Игроки могут оставаться в игре, если другой вышел
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Игра должна завершаться либо победой одого из игроков, либо ничьей
  - Должно быть форматирование языка программирования 
